sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: KUCr6UwMw+huVY1PwcsDgpM6T2ZiuSCCFvyTlZSAvK6quSJZ/J/wfB3gOuGbO6nt63GwqWxICV2SgXCc3chrvbFDpNC8J6s4luWIFrwd8kZGz24JBIDtR8zq1FIJyx7fNtWx5rkLu2YX/+9E3KJyytbcLg6kylBhr7GsKk4lfYw+NZXJBDrWz1Hi38qd3UTjwXcnxsuezGtrPMwgUlXcuG/yV5PMO4mM9fqpfVFSaDzl8RRxtDyJ0Lojwi5v8398cz1ZVN+3zCJe8p9P4562hL1sZFS86V7FP9Mn8FNSGnMTQIXpuhA5NyU3fWFA//wY4zLdSqhmNJ4Yg4sIZY/MhlZMAlCIPRrqsnYIUyAbAUqS/PGR7QIVILfdZZG+G7dIprN5hGMufGJtmQFWTxGcjmvZl7FNBTxlkJWTbGiG/qAHvLG3zoU1QaTcRPYx8znNBLeR/d+civZgpwTcLhzylMRQGxC9i/b5Q20AH/2h2ZX9X+vDu6NMazrPj3Ba301jtUmp3mm6R1YTkD8SsT2Rqg2jy+pdo0HsTPY8hq/fUFHSudUvaJofdjoM34R7ORnnbzrKsGDaNXPTncQnqHl6aLFEnkfdRpZYrqWz/JvIWe8ezFktLeFFUW2sVSjj15PZKqj2M7TC7Yp2rKJvI7sw5C8ifINemN5RGc1W3kHEANY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Volcanic-Islands_3054
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy